function summaryTable = summarize_repeated_runs(allResults)
% summarize_repeated_runs
% Converts repeated-run metrics into a compact summary table.

n = numel(allResults);

fatigueMAE = nan(n,1);
readinessMAE = nan(n,1);
safetyF1 = nan(n,1);
brierScore = nan(n,1);
violationRate = nan(n,1);
averageUtility = nan(n,1);
fallbackRate = nan(n,1);
stability = nan(n,1);

for k = 1:n
    m = allResults{k}.metrics;
    fatigueMAE(k) = m.fatigueMAE;
    readinessMAE(k) = m.readinessMAE;
    safetyF1(k) = m.safetyF1;
    brierScore(k) = m.brierScore;
    violationRate(k) = m.violationRate;
    averageUtility(k) = m.averageUtility;
    fallbackRate(k) = m.fallbackRate;
    stability(k) = m.recommendationStability;
end

summaryTable = table( ...
    mean(fatigueMAE,'omitnan'), std(fatigueMAE,'omitnan'), ...
    mean(readinessMAE,'omitnan'), std(readinessMAE,'omitnan'), ...
    mean(safetyF1,'omitnan'), std(safetyF1,'omitnan'), ...
    mean(brierScore,'omitnan'), std(brierScore,'omitnan'), ...
    mean(violationRate,'omitnan'), std(violationRate,'omitnan'), ...
    mean(averageUtility,'omitnan'), std(averageUtility,'omitnan'), ...
    mean(fallbackRate,'omitnan'), std(fallbackRate,'omitnan'), ...
    mean(stability,'omitnan'), std(stability,'omitnan'), ...
    'VariableNames', { ...
    'FatigueMAE_Mean','FatigueMAE_SD', ...
    'ReadinessMAE_Mean','ReadinessMAE_SD', ...
    'SafetyF1_Mean','SafetyF1_SD', ...
    'Brier_Mean','Brier_SD', ...
    'ViolationRate_Mean','ViolationRate_SD', ...
    'Utility_Mean','Utility_SD', ...
    'FallbackRate_Mean','FallbackRate_SD', ...
    'Stability_Mean','Stability_SD'});
end
